module Evergreen.Migrate.V2 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Main
import Evergreen.V1.Main.Pages.Model
import Evergreen.V1.Pages.About
import Evergreen.V1.Pages.Apps
import Evergreen.V1.Pages.Counter
import Evergreen.V1.Pages.Home_
import Evergreen.V1.Pages.NotFound_
import Evergreen.V1.Pages.Science.Champagne
import Evergreen.V1.Pages.Science.ReasonWhy
import Evergreen.V1.Pages.Scripta
import Evergreen.V1.Shared
import Evergreen.V1.Shared.Model
import Evergreen.V1.Types
import Evergreen.V2.Main
import Evergreen.V2.Main.Pages.Model
import Evergreen.V2.Pages.About
import Evergreen.V2.Pages.Apps
import Evergreen.V2.Pages.Counter
import Evergreen.V2.Pages.Home_
import Evergreen.V2.Pages.NotFound_
import Evergreen.V2.Pages.Science.Champagne
import Evergreen.V2.Pages.Science.ReasonWhy
import Evergreen.V2.Pages.Scripta
import Evergreen.V2.Shared
import Evergreen.V2.Shared.Model
import Evergreen.V2.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V2.Types.FrontendModel Evergreen.V2.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V2.Types.BackendModel Evergreen.V2.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V2.Types.FrontendMsg Evergreen.V2.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V2.Types.ToBackend Evergreen.V2.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V2.Types.BackendMsg Evergreen.V2.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V2.Types.ToFrontend Evergreen.V2.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V2.Types.FrontendModel
migrate_Types_FrontendModel old =
    old |> migrate_Main_Model


migrate_Main_Model : Evergreen.V1.Main.Model -> Evergreen.V2.Main.Model
migrate_Main_Model old =
    { key = old.key
    , url = old.url
    , page = old.page |> migrate_Main_Pages_Model_Model
    , layout = old.layout
    , shared = old.shared |> migrate_Shared_Model
    }


migrate_Main_Pages_Model_Model : Evergreen.V1.Main.Pages.Model.Model -> Evergreen.V2.Main.Pages.Model.Model
migrate_Main_Pages_Model_Model old =
    case old of
        Evergreen.V1.Main.Pages.Model.Home_ p0 ->
            Evergreen.V2.Main.Pages.Model.Home_ (p0 |> migrate_Pages_Home__Model)

        Evergreen.V1.Main.Pages.Model.About p0 ->
            Evergreen.V2.Main.Pages.Model.About (p0 |> migrate_Pages_About_Model)

        Evergreen.V1.Main.Pages.Model.Apps p0 ->
            Evergreen.V2.Main.Pages.Model.Apps (p0 |> migrate_Pages_Apps_Model)

        Evergreen.V1.Main.Pages.Model.Counter p0 ->
            Evergreen.V2.Main.Pages.Model.Counter (p0 |> migrate_Pages_Counter_Model)

        Evergreen.V1.Main.Pages.Model.Photos_Paris ->
            Evergreen.V2.Main.Pages.Model.Photos_Paris

        Evergreen.V1.Main.Pages.Model.Science_Champagne p0 ->
            Evergreen.V2.Main.Pages.Model.Science_Champagne (p0 |> migrate_Pages_Science_Champagne_Model)

        Evergreen.V1.Main.Pages.Model.Science_ReasonWhy p0 ->
            Evergreen.V2.Main.Pages.Model.Science_ReasonWhy (p0 |> migrate_Pages_Science_ReasonWhy_Model)

        Evergreen.V1.Main.Pages.Model.Scripta p0 ->
            Evergreen.V2.Main.Pages.Model.Scripta (p0 |> migrate_Pages_Scripta_Model)

        Evergreen.V1.Main.Pages.Model.NotFound_ p0 ->
            Evergreen.V2.Main.Pages.Model.NotFound_ (p0 |> migrate_Pages_NotFound__Model)

        Evergreen.V1.Main.Pages.Model.Redirecting_ ->
            Evergreen.V2.Main.Pages.Model.Redirecting_

        Evergreen.V1.Main.Pages.Model.Loading_ ->
            Evergreen.V2.Main.Pages.Model.Loading_


migrate_Pages_About_Model : Evergreen.V1.Pages.About.Model -> Evergreen.V2.Pages.About.Model
migrate_Pages_About_Model old =
    old


migrate_Pages_Apps_Model : Evergreen.V1.Pages.Apps.Model -> Evergreen.V2.Pages.Apps.Model
migrate_Pages_Apps_Model old =
    old


migrate_Pages_Counter_Model : Evergreen.V1.Pages.Counter.Model -> Evergreen.V2.Pages.Counter.Model
migrate_Pages_Counter_Model old =
    old


migrate_Pages_Home__Model : Evergreen.V1.Pages.Home_.Model -> Evergreen.V2.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_NotFound__Model : Evergreen.V1.Pages.NotFound_.Model -> Evergreen.V2.Pages.NotFound_.Model
migrate_Pages_NotFound__Model old =
    old


migrate_Pages_Science_Champagne_Model : Evergreen.V1.Pages.Science.Champagne.Model -> Evergreen.V2.Pages.Science.Champagne.Model
migrate_Pages_Science_Champagne_Model old =
    { window = { width = 0, height = 0 }
    }


migrate_Pages_Science_ReasonWhy_Model : Evergreen.V1.Pages.Science.ReasonWhy.Model -> Evergreen.V2.Pages.Science.ReasonWhy.Model
migrate_Pages_Science_ReasonWhy_Model old =
    { window = { width = 0, height = 0 }
    }


migrate_Pages_Scripta_Model : Evergreen.V1.Pages.Scripta.Model -> Evergreen.V2.Pages.Scripta.Model
migrate_Pages_Scripta_Model old =
    { window = { width = 0, height = 0 }
    }


migrate_Shared_Model : Evergreen.V1.Shared.Model -> Evergreen.V2.Shared.Model
migrate_Shared_Model old =
    old |> migrate_Shared_Model_Model


migrate_Shared_Model_Model : Evergreen.V1.Shared.Model.Model -> Evergreen.V2.Shared.Model.Model
migrate_Shared_Model_Model old =
    { smashedLikes = old.smashedLikes
    , window =
        old.window
            |> (\rec -> rec)
    }
