module Evergreen.Migrate.V3 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V2.Main
import Evergreen.V2.Main.Pages.Model
import Evergreen.V2.Main.Pages.Msg
import Evergreen.V2.Pages.About
import Evergreen.V2.Pages.Apps
import Evergreen.V2.Pages.Counter
import Evergreen.V2.Pages.Home_
import Evergreen.V2.Pages.NotFound_
import Evergreen.V2.Pages.Scripta
import Evergreen.V2.Render.Msg
import Evergreen.V2.Shared
import Evergreen.V2.Shared.Model
import Evergreen.V2.Shared.Msg
import Evergreen.V2.Types
import Evergreen.V3.Main
import Evergreen.V3.Main.Pages.Model
import Evergreen.V3.Main.Pages.Msg
import Evergreen.V3.Pages.About
import Evergreen.V3.Pages.Apps
import Evergreen.V3.Pages.Counter
import Evergreen.V3.Pages.Home_
import Evergreen.V3.Pages.NotFound_
import Evergreen.V3.Pages.Scripta
import Evergreen.V3.Render.Msg
import Evergreen.V3.Shared
import Evergreen.V3.Shared.Model
import Evergreen.V3.Shared.Msg
import Evergreen.V3.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V2.Types.FrontendModel -> ModelMigration Evergreen.V3.Types.FrontendModel Evergreen.V3.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V2.Types.BackendModel -> ModelMigration Evergreen.V3.Types.BackendModel Evergreen.V3.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V2.Types.FrontendMsg -> MsgMigration Evergreen.V3.Types.FrontendMsg Evergreen.V3.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V2.Types.ToBackend -> MsgMigration Evergreen.V3.Types.ToBackend Evergreen.V3.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V2.Types.BackendMsg -> MsgMigration Evergreen.V3.Types.BackendMsg Evergreen.V3.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V2.Types.ToFrontend -> MsgMigration Evergreen.V3.Types.ToFrontend Evergreen.V3.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V2.Types.FrontendModel -> Evergreen.V3.Types.FrontendModel
migrate_Types_FrontendModel old =
    old |> migrate_Main_Model


migrate_Types_FrontendMsg : Evergreen.V2.Types.FrontendMsg -> Evergreen.V3.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    old |> migrate_Main_Msg


migrate_Main_Model : Evergreen.V2.Main.Model -> Evergreen.V3.Main.Model
migrate_Main_Model old =
    { key = old.key
    , url = old.url
    , page = old.page |> migrate_Main_Pages_Model_Model
    , layout = old.layout
    , shared = old.shared |> migrate_Shared_Model
    }


migrate_Main_Msg : Evergreen.V2.Main.Msg -> Evergreen.V3.Main.Msg
migrate_Main_Msg old =
    case old of
        Evergreen.V2.Main.UrlRequested p0 ->
            Evergreen.V3.Main.UrlRequested p0

        Evergreen.V2.Main.UrlChanged p0 ->
            Evergreen.V3.Main.UrlChanged p0

        Evergreen.V2.Main.Page p0 ->
            Evergreen.V3.Main.Page (p0 |> migrate_Main_Pages_Msg_Msg)

        Evergreen.V2.Main.Layout p0 ->
            Evergreen.V3.Main.Layout p0

        Evergreen.V2.Main.Shared p0 ->
            Evergreen.V3.Main.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V2.Main.Batch p0 ->
            Evergreen.V3.Main.Batch (p0 |> List.map migrate_Main_Msg)


migrate_Main_Pages_Model_Model : Evergreen.V2.Main.Pages.Model.Model -> Evergreen.V3.Main.Pages.Model.Model
migrate_Main_Pages_Model_Model old =
    case old of
        Evergreen.V2.Main.Pages.Model.Home_ p0 ->
            Evergreen.V3.Main.Pages.Model.Home_ (p0 |> migrate_Pages_Home__Model)

        Evergreen.V2.Main.Pages.Model.About p0 ->
            Evergreen.V3.Main.Pages.Model.About (p0 |> migrate_Pages_About_Model)

        Evergreen.V2.Main.Pages.Model.Apps p0 ->
            Evergreen.V3.Main.Pages.Model.Apps (p0 |> migrate_Pages_Apps_Model)

        Evergreen.V2.Main.Pages.Model.Counter p0 ->
            Evergreen.V3.Main.Pages.Model.Counter (p0 |> migrate_Pages_Counter_Model)

        Evergreen.V2.Main.Pages.Model.Photos_Paris ->
            Evergreen.V3.Main.Pages.Model.Photos_Paris

        Evergreen.V2.Main.Pages.Model.Scripta p0 ->
            Evergreen.V3.Main.Pages.Model.Scripta (p0 |> migrate_Pages_Scripta_Model)

        Evergreen.V2.Main.Pages.Model.NotFound_ p0 ->
            Evergreen.V3.Main.Pages.Model.NotFound_ (p0 |> migrate_Pages_NotFound__Model)

        Evergreen.V2.Main.Pages.Model.Redirecting_ ->
            Evergreen.V3.Main.Pages.Model.Redirecting_

        Evergreen.V2.Main.Pages.Model.Loading_ ->
            Evergreen.V3.Main.Pages.Model.Loading_


migrate_Main_Pages_Msg_Msg : Evergreen.V2.Main.Pages.Msg.Msg -> Evergreen.V3.Main.Pages.Msg.Msg
migrate_Main_Pages_Msg_Msg old =
    case old of
        Evergreen.V2.Main.Pages.Msg.Home_ p0 ->
            Evergreen.V3.Main.Pages.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V2.Main.Pages.Msg.About p0 ->
            Evergreen.V3.Main.Pages.Msg.About (p0 |> migrate_Pages_About_Msg)

        Evergreen.V2.Main.Pages.Msg.Apps p0 ->
            Evergreen.V3.Main.Pages.Msg.Apps (p0 |> migrate_Pages_Apps_Msg)

        Evergreen.V2.Main.Pages.Msg.Counter p0 ->
            Evergreen.V3.Main.Pages.Msg.Counter (p0 |> migrate_Pages_Counter_Msg)

        Evergreen.V2.Main.Pages.Msg.Photos_Paris ->
            Evergreen.V3.Main.Pages.Msg.Photos_Paris

        Evergreen.V2.Main.Pages.Msg.Scripta p0 ->
            Evergreen.V3.Main.Pages.Msg.Scripta (p0 |> migrate_Pages_Scripta_Msg)

        Evergreen.V2.Main.Pages.Msg.NotFound_ p0 ->
            Evergreen.V3.Main.Pages.Msg.NotFound_ (p0 |> migrate_Pages_NotFound__Msg)


migrate_Pages_About_Model : Evergreen.V2.Pages.About.Model -> Evergreen.V3.Pages.About.Model
migrate_Pages_About_Model old =
    old


migrate_Pages_About_Msg : Evergreen.V2.Pages.About.Msg -> Evergreen.V3.Pages.About.Msg
migrate_Pages_About_Msg old =
    case old of
        Evergreen.V2.Pages.About.Render p0 ->
            Evergreen.V3.Pages.About.Render (p0 |> migrate_Render_Msg_MarkupMsg)


migrate_Pages_Apps_Model : Evergreen.V2.Pages.Apps.Model -> Evergreen.V3.Pages.Apps.Model
migrate_Pages_Apps_Model old =
    old


migrate_Pages_Apps_Msg : Evergreen.V2.Pages.Apps.Msg -> Evergreen.V3.Pages.Apps.Msg
migrate_Pages_Apps_Msg old =
    case old of
        Evergreen.V2.Pages.Apps.Render p0 ->
            Evergreen.V3.Pages.Apps.Render (p0 |> migrate_Render_Msg_MarkupMsg)


migrate_Pages_Counter_Model : Evergreen.V2.Pages.Counter.Model -> Evergreen.V3.Pages.Counter.Model
migrate_Pages_Counter_Model old =
    old


migrate_Pages_Counter_Msg : Evergreen.V2.Pages.Counter.Msg -> Evergreen.V3.Pages.Counter.Msg
migrate_Pages_Counter_Msg old =
    case old of
        Evergreen.V2.Pages.Counter.UserClickedIncrement ->
            Evergreen.V3.Pages.Counter.UserClickedIncrement

        Evergreen.V2.Pages.Counter.UserClickedDecrement ->
            Evergreen.V3.Pages.Counter.UserClickedDecrement


migrate_Pages_Home__Model : Evergreen.V2.Pages.Home_.Model -> Evergreen.V3.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_Home__Msg : Evergreen.V2.Pages.Home_.Msg -> Evergreen.V3.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V2.Pages.Home_.Render p0 ->
            Evergreen.V3.Pages.Home_.Render (p0 |> migrate_Render_Msg_MarkupMsg)


migrate_Pages_NotFound__Model : Evergreen.V2.Pages.NotFound_.Model -> Evergreen.V3.Pages.NotFound_.Model
migrate_Pages_NotFound__Model old =
    old


migrate_Pages_NotFound__Msg : Evergreen.V2.Pages.NotFound_.Msg -> Evergreen.V3.Pages.NotFound_.Msg
migrate_Pages_NotFound__Msg old =
    case old of
        Evergreen.V2.Pages.NotFound_.NoOp ->
            Evergreen.V3.Pages.NotFound_.NoOp


migrate_Pages_Scripta_Model : Evergreen.V2.Pages.Scripta.Model -> Evergreen.V3.Pages.Scripta.Model
migrate_Pages_Scripta_Model old =
    old


migrate_Pages_Scripta_Msg : Evergreen.V2.Pages.Scripta.Msg -> Evergreen.V3.Pages.Scripta.Msg
migrate_Pages_Scripta_Msg old =
    case old of
        Evergreen.V2.Pages.Scripta.Render p0 ->
            Evergreen.V3.Pages.Scripta.Render (p0 |> migrate_Render_Msg_MarkupMsg)


migrate_Render_Msg_Handling : Evergreen.V2.Render.Msg.Handling -> Evergreen.V3.Render.Msg.Handling
migrate_Render_Msg_Handling old =
    case old of
        Evergreen.V2.Render.Msg.MHStandard ->
            Evergreen.V3.Render.Msg.MHStandard

        Evergreen.V2.Render.Msg.MHAsCheatSheet ->
            Evergreen.V3.Render.Msg.MHAsCheatSheet


migrate_Render_Msg_MarkupMsg : Evergreen.V2.Render.Msg.MarkupMsg -> Evergreen.V3.Render.Msg.MarkupMsg
migrate_Render_Msg_MarkupMsg old =
    case old of
        Evergreen.V2.Render.Msg.SendMeta p0 ->
            Evergreen.V3.Render.Msg.SendMeta p0

        Evergreen.V2.Render.Msg.SendLineNumber p0 ->
            Evergreen.V3.Render.Msg.SendLineNumber p0

        Evergreen.V2.Render.Msg.SelectId p0 ->
            Evergreen.V3.Render.Msg.SelectId p0

        Evergreen.V2.Render.Msg.HighlightId p0 ->
            Evergreen.V3.Render.Msg.HighlightId p0

        Evergreen.V2.Render.Msg.GetPublicDocument p0 p1 ->
            Evergreen.V3.Render.Msg.GetPublicDocument (p0 |> migrate_Render_Msg_Handling) p1

        Evergreen.V2.Render.Msg.GetPublicDocumentFromAuthor p0 p1 p2 ->
            Evergreen.V3.Render.Msg.GetPublicDocumentFromAuthor (p0 |> migrate_Render_Msg_Handling) p1 p2

        Evergreen.V2.Render.Msg.GetDocumentWithSlug p0 p1 ->
            Evergreen.V3.Render.Msg.GetDocumentWithSlug (p0 |> migrate_Render_Msg_Handling) p1

        Evergreen.V2.Render.Msg.ProposeSolution p0 ->
            Evergreen.V3.Render.Msg.ProposeSolution (p0 |> migrate_Render_Msg_SolutionState)

        Evergreen.V2.Render.Msg.RequestCopyOfDocument ->
            Evergreen.V3.Render.Msg.RequestCopyOfDocument

        Evergreen.V2.Render.Msg.RequestToggleIndexSize ->
            Evergreen.V3.Render.Msg.RequestToggleIndexSize

        Evergreen.V2.Render.Msg.JumpToTop ->
            Evergreen.V3.Render.Msg.JumpToTop

        Evergreen.V2.Render.Msg.MMNoOp ->
            Evergreen.V3.Render.Msg.MMNoOp


migrate_Render_Msg_SolutionState : Evergreen.V2.Render.Msg.SolutionState -> Evergreen.V3.Render.Msg.SolutionState
migrate_Render_Msg_SolutionState old =
    case old of
        Evergreen.V2.Render.Msg.Unsolved ->
            Evergreen.V3.Render.Msg.Unsolved

        Evergreen.V2.Render.Msg.Solved p0 ->
            Evergreen.V3.Render.Msg.Solved p0


migrate_Shared_Model : Evergreen.V2.Shared.Model -> Evergreen.V3.Shared.Model
migrate_Shared_Model old =
    old |> migrate_Shared_Model_Model


migrate_Shared_Model_Model : Evergreen.V2.Shared.Model.Model -> Evergreen.V3.Shared.Model.Model
migrate_Shared_Model_Model old =
    old


migrate_Shared_Msg : Evergreen.V2.Shared.Msg -> Evergreen.V3.Shared.Msg
migrate_Shared_Msg old =
    old |> migrate_Shared_Msg_Msg


migrate_Shared_Msg_Msg : Evergreen.V2.Shared.Msg.Msg -> Evergreen.V3.Shared.Msg.Msg
migrate_Shared_Msg_Msg old =
    case old of
        Evergreen.V2.Shared.Msg.GotNewSmashedLikes p0 ->
            Evergreen.V3.Shared.Msg.GotNewSmashedLikes p0
